options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'function-2'
      - '--region'
      - 'us-central1'
      - '--runtime'
      - 'python39'
      - '--trigger-http'
      - '--entry-point'
      - 'hello_http' 
      - '--source'
      - '.'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'describe'
      - 'function-2'
      - '--region'
      - 'us-central1'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'list'
      - '--region'
      - 'us-central1'
      - '--format'
      - 'json'